"""QUANTITATIVE_GROUNDING.md ↔ grounding.py drift 차단 (pytest 강제).

생성기 scripts/gen_quantitative_grounding.py 가 grounding.py(GROUNDED/SOURCES) 정본에서 doc 을
*생성*한다 → 이 테스트가 render()==disk 를 강제해 drift 를 구조적으로 불가능하게 한다.
(--check CLI 가드는 CI 전용; 이 테스트는 일반 pytest 경로에서도 강제.)
work-item: assessment Q2-A "doc tier 불일치·생성기 부재" 회귀 차단. tier 정직면책은 코드가 정본
(doc 가 코드를 따라간다) — 면책을 '정리'하지 않는다.
# KG: span_lakatotree_grounding
"""
import importlib.util
import sys
from pathlib import Path

# scripts/ 는 __init__.py 부재 + pytest rootdir/pythonpath config 전무 → import 성립 필수 전제
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def _load_generator():
    spec = importlib.util.spec_from_file_location(
        "_genq", ROOT / "scripts" / "gen_quantitative_grounding.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


DOC = ROOT / "docs" / "QUANTITATIVE_GROUNDING.md"


def test_doc_is_in_sync_with_generator():
    gen = _load_generator()
    rendered = gen.render()
    disk = DOC.read_text(encoding="utf-8")
    assert rendered == disk, (
        "QUANTITATIVE_GROUNDING.md 가 grounding.py 정본과 drift — "
        "재생성: python scripts/gen_quantitative_grounding.py")


def test_every_grounded_constant_appears_in_doc():
    gen = _load_generator()
    from lakatos.grounding import GROUNDED
    rendered = gen.render()
    missing = [k for k in GROUNDED if f"`{k}`" not in rendered]
    assert not missing, f"생성기가 상수 누락(가짜 정밀 위험): {missing}"


def test_doc_claims_autogenerated_and_generator_exists():
    # (c) '자동생성 표기인데 생성기 부재' 회귀 차단
    assert (ROOT / "scripts" / "gen_quantitative_grounding.py").exists()
    disk = DOC.read_text(encoding="utf-8")
    assert "gen_quantitative_grounding.py" in disk and "자동생성" in disk


def test_tier_summary_reflects_code_not_doc():
    # tier 는 코드(GROUNDED[k]['tier'])가 정본 — doc 의 tier 요약이 코드서 도출됨을 확인
    gen = _load_generator()
    from lakatos.grounding import GROUNDED
    rendered = gen.render()
    # 코드가 policy_in_scale 로 강등한 상수가 doc 에 literature 로 둔갑하지 않음
    for k in ("eigentrust_alpha", "ece_bins"):
        if k in GROUNDED:
            assert GROUNDED[k]["tier"] == "policy_in_scale"
            assert f"`{k}`" in rendered
