"""라카토트리 순수 엔진 패키지."""

from lakatos.engine import (
    BashAct,
    CredibilityPromotionGate,
    CredibilityTier,
    EmbeddedInternetEvidence,
    FoundationGate,
    FoundationMap,
    FoundationRequirement,
    GateResult,
    InternetObservation,
    KnowledgeKind,
    LakatosEvidence,
    LakatosGate,
    LakatosGateResult,
    LakatosNode,
    LakatosTree,
    LakatosVerdict,
    LonginusRef,
    ObservationLedger,
    Possibility,
    Realm,
    ResearchEvent,
    ResearchFrame,
    ResearchProject,
    RivalProgrammeLink,
    RivalRelation,
    SourceCredibilityScore,
    TheoryEmbedding,
)
from lakatos.io.replay import LineageReplayGate, LineageReplayResult, ReproducibilityContract
from lakatos.claim import (
    ClaimNextAction,
    ClaimStanding,
    ClaimStandingPolicy,
    evaluate_claim_standing,
)
from lakatos.io.lineage import (
    DatasetManifest,
    DatasetManifestResult,
    Derivation,
    EnvironmentFingerprint,
    dataset_manifest_from_derivations,
    fingerprint_environment,
    load_dataset_manifest,
    manifest_from_dict,
    manifest_to_dict,
    verify_dataset_manifest,
)
from lakatos.io.adapters import (
    MarquezClientError,
    bash_act_to_prov_document,
    derivation_to_openlineage_event,
    derivations_to_dvc_lock,
    derivations_to_dvc_pipeline,
    derivations_to_prov_document,
    lineage_result_to_openlineage_events,
    observation_to_prov_document,
    prov_document_to_prov_json,
    rebuild_recipe_manifest,
    send_openlineage_events_to_marquez,
    serialize_prov_document,
)
from lakatos.verdicts import (
    ADMIN_VERDICTS,
    SCRIPTED_VERDICTS,
    VERDICT_REGISTRY,
    is_admin_verdict,
    is_registered_verdict,
    is_scripted_verdict,
)
from lakatos.programme.stack import LayerVote, StackVerdict, evaluate_stack, stack_verdict
from lakatos.programme.agm import Belief, HardCoreProtected, RevisionResult, contraction, demote_canonical, expansion, revision
from lakatos.programme.lifecycle import LifecycleState, lifecycle_state, regret_nodes
from lakatos.programme.leaderboard import Competitor, dominates, leaderboard, score_competitor
from lakatos.programme.kuhn import ParadigmAssessment, assess_paradigm, sustained_dominance
from lakatos.programme.series import ProgrammeSeriesAppraisal, ProgrammeSeriesRecord, programme_series_appraisal
from lakatos.verdict.certify import Certificate, GateCheck, certify_claim, gate_check, next_actions
from lakatos.world_gates import scan_prompt_injection, web_gate, world_action_gate, LAKATOS_LOCATIONS
from lakatos.semantic_surface import SemanticSurfaceReport, SemanticUnit, load_surface, validate_surface
from lakatos.eureka import EurekaVerdict, classify, eureka_over_tree, eureka_rate

__all__ = [
    "scan_prompt_injection",
    "web_gate",
    "world_action_gate",
    "LAKATOS_LOCATIONS",
    "BashAct",
    "CredibilityPromotionGate",
    "CredibilityTier",
    "EmbeddedInternetEvidence",
    "FoundationGate",
    "FoundationMap",
    "FoundationRequirement",
    "GateResult",
    "InternetObservation",
    "KnowledgeKind",
    "LakatosEvidence",
    "LakatosGate",
    "LakatosGateResult",
    "LakatosNode",
    "LakatosTree",
    "LakatosVerdict",
    "LonginusRef",
    "LineageReplayGate",
    "LineageReplayResult",
    "ObservationLedger",
    "Possibility",
    "Realm",
    "ReproducibilityContract",
    "ResearchEvent",
    "ResearchFrame",
    "ResearchProject",
    "RivalProgrammeLink",
    "RivalRelation",
    "SourceCredibilityScore",
    "TheoryEmbedding",
    "ClaimNextAction",
    "ClaimStanding",
    "ClaimStandingPolicy",
    "evaluate_claim_standing",
    "DatasetManifest",
    "DatasetManifestResult",
    "Derivation",
    "EnvironmentFingerprint",
    "dataset_manifest_from_derivations",
    "fingerprint_environment",
    "load_dataset_manifest",
    "manifest_from_dict",
    "manifest_to_dict",
    "verify_dataset_manifest",
    "MarquezClientError",
    "ADMIN_VERDICTS",
    "SCRIPTED_VERDICTS",
    "VERDICT_REGISTRY",
    "is_admin_verdict",
    "is_registered_verdict",
    "is_scripted_verdict",
    "bash_act_to_prov_document",
    "derivation_to_openlineage_event",
    "derivations_to_dvc_lock",
    "derivations_to_dvc_pipeline",
    "derivations_to_prov_document",
    "lineage_result_to_openlineage_events",
    "observation_to_prov_document",
    "prov_document_to_prov_json",
    "rebuild_recipe_manifest",
    "send_openlineage_events_to_marquez",
    "serialize_prov_document",
    "LayerVote",
    "StackVerdict",
    "evaluate_stack",
    "stack_verdict",
    "Belief",
    "HardCoreProtected",
    "RevisionResult",
    "contraction",
    "demote_canonical",
    "expansion",
    "revision",
    "LifecycleState",
    "lifecycle_state",
    "regret_nodes",
    "Competitor",
    "dominates",
    "leaderboard",
    "score_competitor",
    "ParadigmAssessment",
    "assess_paradigm",
    "sustained_dominance",
    "ProgrammeSeriesAppraisal",
    "ProgrammeSeriesRecord",
    "programme_series_appraisal",
    "Certificate",
    "GateCheck",
    "certify_claim",
    "gate_check",
    "next_actions",
    "SemanticSurfaceReport",
    "SemanticUnit",
    "load_surface",
    "validate_surface",
    "EurekaVerdict",
    "classify",
    "eureka_over_tree",
    "eureka_rate",
]
